import Header from "./Header";
import Footer from "./Footer";
import Home from "./Home";
import About from "./About";
import Contact from "./Contact";
import User from "./User";
import Github from "./Github";
export { Header }
export { Footer }
export { Home }
export { About }
export { Contact }
export { User }
export { Github }